version: '3.8'

services:
  # 1. Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_distribuido
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: distribuida_db
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mi-red-app

  # 2. Backend Node.js
  node-api:
    build: ./backend-node
    container_name: node_service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: distribuida_db
    depends_on:
      - db
    networks:
      - mi-red-app

  # 3. Backend .NET
  net-api:
    build: ./backend-net
    container_name: net_service
    ports:
      - "5000:8080" # <--- CORREGIDO: AgreguÃ© el guion '-' que faltaba
    networks:
      - mi-red-app

  # 4. BASE DE DATOS POSTGRES (Nuevo)
  db-postgres:
    image: postgres:15-alpine
    container_name: contenedor_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mi-red-app

  # 5. SERVICIO PHP (API) (Nuevo)
  php-service:
    build: ./php-api
    container_name: contenedor_php
    ports:
      - "8000:80"
    volumes:
      - ./php-api/src:/var/www/html
    depends_on:
      - db-postgres
    networks:
      - mi-red-app

volumes:
  pgdata:

networks:
  mi-red-app:
    driver: bridge